[package]
name = "r2d2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
regex = "1"
colored = "2"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
